services:
  api:
    image: api
    build:
      context: ./hospital-a.api
    # ไม่กำหนด ports เพื่อให้ scale ได้
    env_file: ./hospital-a.api/.env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"  # เปลี่ยนเป็น standard HTTP port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # ปรับให้ชี้ไปที่ไฟล์ config หลัก
      - ./nginx/conf.d:/etc/nginx/conf.d  # เพิ่ม volume สำหรับ config directories
    depends_on:
      - api

volumes:
  db-data:
  pgadmin-data: